---
# Install IBM Spectrum Scale (GPFS)

- import_tasks: scale_check.yml
  tags: always

- import_tasks: scale_prepare.yml
  tags: prepare

- import_tasks: scale_install.yml
  tags: install

- import_tasks: scale_build.yml
  tags: build

- import_tasks: scale_cluster.yml
  tags: cluster

# Future:
# - scale_storage.yml
# - scale_filesystem.yml
