---
# Install and configure IBM Spectrum Scale (GPFS)

- import_tasks: check.yml
  tags: always

- import_tasks: prepare.yml
  tags: prepare

- import_tasks: install.yml
  tags: install

- import_tasks: build.yml
  tags: build

- import_tasks: cluster.yml
  tags: cluster

- import_tasks: config.yml
  tags: config

- import_tasks: cluster_start.yml
  tags: cluster

- import_tasks: storage.yml
  tags: storage

- import_tasks: finalize.yml
  tags: always
