---
# Remote package installation method

- name: Check installation package on remote machine
  assert:
    that:
      - scale_install_remotepkg_path is defined
      - scale_install_remotepkg_path | is_file
    msg: "Please set the variable 'scale_install_remotepkg_path' to point to the remote installation package!"
  run_once: true

...
