---
# YUM repository installation method

#
# Configure YUM repository
#
- name: install | Configure YUM repository
  yum_repository:
    name: spectrum-scale
    description: IBM Spectrum Scale (GPFS)
    baseurl: "{{ scale_install_repository_url }}"
    gpgcheck: no
    state: present
  when: ansible_pkg_mgr == 'yum'

#
# Ensure no daemon running
#
- name: install | Count daemon processes
  command: pgrep mmfsd
  register: scale_install_daemonprocs
  changed_when: false
  failed_when: false

- name: install | Check daemon processes
  debug: msg="Spectrum Scale is running. Please stop it for an upgrade!"
  when: scale_install_daemonprocs.rc == 0

# TODO: If GPFS already installed check version and compare with scale_version

#
# Install RPMs
#
- block:  ## when: scale_install_daemonprocs.rc == 1
    - name: install | Install GPFS RPMs
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: present
      when: ansible_pkg_mgr == 'yum'
      with_items:
        - "{{ scale_install_gpfs_rpms }}"
        - gpfs.gskit
  when: scale_install_daemonprocs.rc == 1


# TODO: online upgrade
# ... serial ...
# - block:
#     - stop GPFS on node
#     - upgrade GPFS rpms
#   rescue:
#     - debug: msg='Can't upgrade GPFS!'
#   always:
#     - start GPFS on node
