---
# YUM repository installation method

#
# Configure YUM repository
#
- name: install | Configure YUM repository
  yum_repository:
    name: spectrum-scale-gpfs
    description: IBM Spectrum Scale (GPFS)
    baseurl: "{{ scale_install_repository_url }}"
    gpgcheck: no
    state: present
  notify: yum-clean-metadata
  when: ansible_pkg_mgr == 'yum'

- meta: flush_handlers

#
# Fail upon online update
#
- include_tasks: scale_update.yml
  when: scale_daemon_running == true

#
# Install or update RPMs
#
- block:  ## when: scale_daemon_running == false
    - name: install | List installed GPFS RPMs
      yum:
        list: gpfs.base
        disablerepo: spectrum-scale-gpfs
      register: scale_install_rpmlist
      when: ansible_pkg_mgr == 'yum'

    - name: install | Install GPFS RPMs
      yum:
        name: "{{ item }}"
        state: present
      register: scale_install_rpmresult
      when: ansible_pkg_mgr == 'yum'
      with_items:
        - "{{ scale_install_gpfs_rpms }}"
        - gpfs.gskit

    - name: install | Check if GPFS RPMs were updated
      set_fact:
        scale_install_updated: true
      when:
        - "'installed' in scale_install_rpmlist.results | map(attribute='yumstate') | list"
        - scale_install_rpmresult.changed

    - name: install | Install GPFS RPMs for building GPL module from source
      yum:
        name: "{{ item }}"
        state: present
      when:
        - ansible_pkg_mgr == 'yum'
        - scale_build_gplbin_rpm is undefined
      with_items: "{{ scale_install_gplsrc_rpms }}"
  when: scale_daemon_running == false
