---
# Inform user about (offline) update

- name: update | Find current version
  shell: /usr/lpp/mmfs/bin/mmdiag --version -Y | grep -v HEADER | cut -d ':' -f 7 | tr -d '[:space:]'
  register: scale_current_version
  changed_when: false
  failed_when: false

- name: update | Check if node needs to be updated
  set_fact:
    scale_install_needsupdate: "{{ scale_current_version.stdout != scale_version }}"

- block:  ## run_once: true
    - name: update | Check if any running node needs to be updated
      vars:
        msg: |-
          ######################################################################
          Spectrum Scale current version is "{{ scale_current_version.stdout }}" available version for upgrade "{{ scale_version }}"
          Spectrum Scale is running, Please stop it for an automatic offline update,
          or manually perform an online update (by taking down one node at a time)!
          ######################################################################
      assert:
        that:
          - true not in ansible_play_hosts | map('extract', hostvars, 'scale_install_needsupdate') | list
        msg: "{{ msg }}"
        ##todo regression: assert msg no longer accepts list #48547 Another option to configure this is to add stdout_callback = debug to your ansible.cfg
  run_once: true
