---
# Build Linux kernel extension from source

- block:  ## when: scale_install_gplbin_rpm is undefined
#
# Install gplsrc prereqs
#
    - name: build | Install prereqs for building GPL module from source
      yum:
        name: "{{ scale_build_gplsrc_prereqs }}"
        state: present
      when: ansible_pkg_mgr == 'yum'

#
# Identify Linux Distribution
#
    - name: build | Identify RedHat distribution
      set_fact:
        scale_build_distribution: REDHAT_AS_LINUX
      when: >
        ansible_distribution == 'CentOS' or
        ansible_distribution == 'RedHat'

    #- name: build | Identify Suse distribution
    #  set_fact:
    #    scale_build_distribution: SUSE_LINUX
    #  when: ansible_distribution == 'Suse'

    - name: check | Check Linux distribution
      assert:
        that: scale_build_distribution is defined
        fail_msg: >-
          Unsupported Linux distribution {{ ansible_distribution }}!

#
# Build kernel extension
#
    - name: build | Compile GPL module
      shell: export LINUX_DISTRIBUTION={{ scale_build_distribution }} ; /usr/lpp/mmfs/bin/mmbuildgpl --quiet
      args:
        creates: /lib/modules/{{ ansible_kernel }}/extra/mmfs26.ko

    - name: build | Stat GPL module
      stat:
        path: /lib/modules/{{ ansible_kernel }}/extra/mmfs26.ko
      register: scale_build_kmod

    - name: build | Check GPL module
      assert:
        that: scale_build_kmod.stat.exists
        fail_msg: >-
          Unable to build Linux kernel extension for running kernel
          {{ ansible_kernel }}!
  when: scale_install_gplbin_rpm is undefined
