---
# Inform user about (offline) update

- name: update | Find current version
  shell: "/usr/lpp/mmfs/bin/mmdiag --version -Y | grep -v HEADER | cut -d ':' -f 7 | tr -d '[:space:]'"
  register: scale_current_version
  changed_when: false
  failed_when: false

# TODO: print this message at the end of the play (set_fact)
- name: update | Compare versions
  debug: msg="Spectrum Scale is running. Please stop it for an update!"
  when: scale_version != scale_current_version.stdout
