---
# Print messages collected during play

- block:  ## run_once: true
    - name: finalize | Check if GPFS was updated
      vars:
        msg: |-
          ######################################################################
          Spectrum Scale packages were updated. Once all nodes in the cluster
          run the new version, consider updating configuration information to
          the latest format that is supported by the currently installed level:

            mmchconfig release=LATEST

          Furthermore, consider updating the file systems to the latest format
          that is supported by the currently installed level:

            mmchfs fs1 -V full

          Remember that nodes in remote clusters running an older version will
          no longer be able to mount the file system!
          ######################################################################
      debug:
        msg: "{{ msg.split('\n') }}"
      when: true in ansible_play_hosts | map('extract', hostvars, 'scale_install_updated') | list

    - name: finalize | Check if config params were changed
      vars:
        msg: |-
          ######################################################################
          Configuration parameters were changed. Please restart Spectrum Scale
          on all nodes for the new settings to take effect!
          ######################################################################
      debug:
        msg: "{{ msg.split('\n') }}"
      when: true in ansible_play_hosts | map('extract', hostvars, 'scale_config_changed') | list
  run_once: true
