---
# Inform user about (offline) update

- name: update | Find current version
  shell: "/usr/lpp/mmfs/bin/mmdiag --version -Y | grep -v HEADER | cut -d ':' -f 7 | tr -d '[:space:]'"
  register: scale_current_version
  changed_when: false
  failed_when: false

# TODO: fail if GPFS is running on >= one node
- name: update | Compare versions
  assert:
    that: scale_version == scale_current_version.stdout
    msg: Spectrum Scale is running. Please stop it for an update!
