---
# Start daemon on new nodes (candidates)

- name: cluster-start | Start daemons
  command: /usr/lpp/mmfs/bin/mmstartup -N localhost
  when: "'scale_cluster_candidates' in group_names"
  notify: wait-daemon-active

- meta: flush_handlers
