---
# Build Linux kernel extension

#
# Install prereqs
#
- name: build | Install build prereqs
  yum: name={{ item }} state=present
  when: ansible_pkg_mgr == 'yum'
  with_items: "{{ scale_build_prereqs }}"

#
# Identify Linux Distribution
#
- name: build | Identify RedHat distribution
  set_fact: scale_build_distribution="REDHAT_AS_LINUX"
  when:
    - ansible_distribution == "CentOS" or
      ansible_distribution == "RedHat"

#- name: build | Identify SUSE distribution
#  set_fact: scale_build_distribution="SUSE_LINUX"
#  when: ansible_distribution == "Suse"

- name: check | Check Linux distribution
  assert:
    that: scale_build_distribution is defined
    msg: "Unsupported Linux distribution ({{ ansible_distribution }})!"

#
# Build kernel extension
#
- name: build | Compile kernel extension
  shell: "LINUX_DISTRIBUTION = {{ scale_build_distribution }} ; /usr/lpp/mmfs/bin/mmbuildgpl --quiet"
  args:
    creates: /lib/modules/{{ ansible_kernel }}/extra/mmfs26.ko

- name: build | Stat kernel extension
  stat: path=/lib/modules/{{ ansible_kernel }}/extra/mmfs26.ko
  register: scale_build_kmod

- name: build | Check kernel extension
  assert:
    that: scale_build_kmod.stat.exists
    msg: "Unable to build Linux kernel extension for running kernel {{ ansible_kernel }}!"
