---
# YUM repository installation method

#
# Configure YUM repository
#
- name: install | Configure YUM repository
  yum_repository:
    name: spectrum-scale-gpfs
    description: IBM Spectrum Scale (GPFS)
    baseurl: "{{ scale_install_repository_url }}"
    gpgcheck: no
    state: present
  when: ansible_pkg_mgr == 'yum'

#
# Fail upon online update
#
- include_tasks: scale_update.yml
  when: scale_daemon_running == true

#
# Install RPMs
#
- block:  ## when: scale_daemon_running == false
    - name: install | Install GPFS RPMs
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: present
      when: ansible_pkg_mgr == 'yum'
      with_items:
        - "{{ scale_install_gpfs_rpms }}"
        - gpfs.gskit

    - name: install | Install GPFS RPMs for building GPL module from source
      yum:
        name: "{{ item }}"
        update_cache: yes
        state: present
      when:
        - ansible_pkg_mgr == 'yum'
        - scale_build_gplbin_rpm is undefined
      with_items: "{{ scale_install_gplsrc_rpms }}"
  when: scale_daemon_running == false


# TODO: online upgrade as separate playbook
# ... serial ...
# - block:
#     - stop GPFS on node
#     - upgrade GPFS rpms
#   rescue:
#     - debug: msg='Can't upgrade GPFS!'
#   always:
#     - start GPFS on node
