---
# Handlers for the IBM Spectrum Scale (GPFS) role

- name: reboot
  fail:
    msg: >-
      A server reboot is required!

- name: reload-sshd
  service:
    name: sshd
    state: reloaded

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: false

- name: accept-server-licenses
  command: /usr/lpp/mmfs/bin/mmchlicense server --accept -N serverLicense
  listen: accept-licenses
  failed_when: false

- name: accept-client-licenses
  command: /usr/lpp/mmfs/bin/mmchlicense client --accept -N clientLicense
  listen: accept-licenses
  failed_when: false

- name: wait-daemon-active
  shell: /usr/lpp/mmfs/bin/mmgetstate -N localhost -Y | grep -v HEADER | cut -d ':' -f 9
  register: state
  until: state.stdout == 'active'
  retries: 10
  delay: 30
  changed_when: false
