---
# Handlers for the IBM Spectrum Scale (GPFS) role

- name: reload-sshd
  service:
    name: sshd
    state: reloaded

- name: reboot-manual
  fail:
    msg: >-
      A server reboot is required!
  listen: reboot
  when: not scale_reboot_automatic

- name: reboot-automatic
  shell: sleep 2 && shutdown -r now "Ansible reboot"
  listen: reboot
  notify: wait-for-server
  when: scale_reboot_automatic
  async: 1
  poll: 0
  ignore_errors: true

- name: wait-for-server
  wait_for:
    host: "{{ ansible_default_ipv4.address }}"
    port: 22
    state: started
    delay: 45
    timeout: 300
  delegate_to: localhost

- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: false

- name: accept-server-licenses
  command: /usr/lpp/mmfs/bin/mmchlicense server --accept -N serverLicense
  listen: accept-licenses
  failed_when: false

- name: accept-client-licenses
  command: /usr/lpp/mmfs/bin/mmchlicense client --accept -N clientLicense
  listen: accept-licenses
  failed_when: false

- name: wait-daemon-active
  shell: /usr/lpp/mmfs/bin/mmgetstate -N localhost -Y | grep -v HEADER | cut -d ':' -f 9
  register: state
  until: state.stdout == 'active'
  retries: 10
  delay: 30
  changed_when: false
